### PR TITLE
Feature/admin operations

### PR DESCRIPTION
**Pull request by abdulaziz-alhashedi**
run 

```
cd backend 

php artisan migrate:fresh --seed

then 

php artisan serve

```

register a new user it will be admin by default

then you login tray to logout and login again

### CODE REVIEW

**Comment by mohamedshaibani** [comment]
Good work,bro

**Review by mohammed-alshaibani — COMMENTED** [review]
good job

**Review by mohammed-alshaibani — COMMENTED** [review]
good

**Review by mohammed-alshaibani — COMMENTED** [review]
good

**Review by mohammed-alshaibani — APPROVED** [review]
done

**Pull request merged**
