### PR TITLE
This commit for strucrt of backend folders

### PR DESCRIPTION
**Pull request by mohammed-alshaibani**
My First Commit for layouts strucure

### CODE REVIEW

**Review by abdulaziz-alhashedi — APPROVED** [review]
Nice work that will make the backend much easier for us

**Review by MuhannedNoman — APPROVED** [review]
LGTM, feel free to merge.

**Comment by ahmedalsanadi** [comment]
Great structure, Mohammed! Just a quick note—please make sure your branch is up to date with the `dev` branch to avoid any merge conflicts. I recommend running `git pull origin dev` before submitting your pull request. Thanks!

**Review by ahmedalsanadi — COMMENTED** [review]
Great structure, Mohammed! Just a quick note—please make sure your branch is up to date with the `dev` branch to avoid any merge conflicts. I recommend running `git pull origin dev` before submitting your pull request. Thanks!

**Pull request closed without merging**
